import { useEffect, useState } from "react";
import { Box, List, ListItemButton, ListItemText, Paper, Snackbar, Typography } from "@mui/material";
import RefreshIcon from "@mui/icons-material/Refresh";
import { listPendingItems, reviewItem } from "../api/workflow";
import PageHeader from "../components/PageHeader";
import Button from "../components/Button";
import Alert from "../components/Alert";
import EmptyState from "../components/EmptyState";
import StatusBadge from "../components/StatusBadge";
import ItemReviewPanel from "../features/approvals/ItemReviewPanel";

const VERB = { approve: "approved", reject: "rejected", edit_and_approve: "edited and approved" };

export default function ApprovalsPage() {
  const [data, setData] = useState({ status: "loading", items: [], error: "" });
  const [reloadKey, setReloadKey] = useState(0);
  const [selectedId, setSelectedId] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [reviewError, setReviewError] = useState("");
  const [notice, setNotice] = useState("");

  useEffect(() => {
    const controller = new AbortController();
    listPendingItems({ signal: controller.signal })
      .then((items) => setData({ status: "ready", items, error: "" }))
      .catch((err) => {
        if (err.name === "AbortError") return;
        setData((current) => ({
          status: "error",
          items: current.items,
          error: err.status ? err.message : "Cannot reach the server",
        }));
      });
    return () => controller.abort();
  }, [reloadKey]);

  const { status, items, error } = data;
  const selected = items.find((item) => item.id === selectedId) ?? items[0] ?? null;

  function refresh() {
    setData((current) => ({ ...current, status: "loading" }));
    setReloadKey((key) => key + 1);
  }

  async function handleReview(review) {
    setSubmitting(true);
    setReviewError("");
    try {
      await reviewItem({ itemId: selected.id, ...review });
      // The item leaves the queue at once; the refresh confirms with the server.
      setData((current) => ({ ...current, items: current.items.filter((item) => item.id !== selected.id) }));
      setNotice(`Item ${VERB[review.decision] ?? "reviewed"}`);
      setReloadKey((key) => key + 1);
    } catch (err) {
      setReviewError(err.status ? err.message : "Cannot reach the server");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <>
      <PageHeader
        title="Approvals"
        description="Nothing generated by the agents is final until it is reviewed here."
        action={
          <Button variant="secondary" startIcon={<RefreshIcon />} onClick={refresh} loading={status === "loading"} loadingText="Refreshing...">
            Refresh
          </Button>
        }
      />

      {status === "error" && (
        <Alert variant="error" sx={{ mb: 2 }}>
          {error}
        </Alert>
      )}

      {items.length === 0 && status !== "loading" ? (
        <Paper variant="outlined" sx={{ borderRadius: 3 }}>
          <EmptyState title="Nothing to review" description="New items appear here when a workflow run finishes generating them." />
        </Paper>
      ) : (
        <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", lg: "340px minmax(0, 1fr)" }, gap: 3, alignItems: "start" }}>
          <Paper variant="outlined" sx={{ p: 2, borderRadius: 3 }}>
            <Typography variant="h6" component="h2" sx={{ fontWeight: 700, mb: 1 }}>
              Waiting for review ({items.length})
            </Typography>
            <List disablePadding sx={{ display: "flex", flexDirection: "column", gap: 0.5 }}>
              {items.map((item) => (
                <ListItemButton
                  key={item.id}
                  selected={item.id === selected?.id}
                  onClick={() => {
                    setSelectedId(item.id);
                    setReviewError("");
                  }}
                  sx={{ borderRadius: 2, alignItems: "flex-start", gap: 1 }}
                >
                  <ListItemText
                    primary={item.moduleTitle || item.question.slice(0, 60) || "Assessment item"}
                    secondary={[item.documentTitle, item.page != null ? `p. ${item.page}` : ""].filter(Boolean).join(" · ") || undefined}
                    slotProps={{ primary: { fontWeight: 600, sx: { overflowWrap: "anywhere" } } }}
                  />
                  <StatusBadge status={item.status} />
                </ListItemButton>
              ))}
            </List>
          </Paper>

          <Box sx={{ display: "flex", flexDirection: "column", gap: 2, minWidth: 0 }}>
            {reviewError && <Alert variant="error">{reviewError}</Alert>}
            {selected && <ItemReviewPanel key={selected.id} item={selected} submitting={submitting} onReview={handleReview} />}
          </Box>
        </Box>
      )}

      <Snackbar open={Boolean(notice)} autoHideDuration={4000} onClose={() => setNotice("")} message={notice} />
    </>
  );
}
